version: "3.6"

services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./support/proxy/nginx.conf:/etc/nginx/nginx.conf:ro

  gateway:
    build: ./support/gateway
    ports:
      - "2222:2222"

  # loophole:
  #   build: ./support/client
  #   command: "sh -c \"sleep 5 && ssh -4 -N -R *:8080:myservice:80 gateway\""

  loophole:
    build: ./loophole

  myservice:
    image: nginx
