version: "3.6"

services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./support/proxy/nginx.conf:/etc/nginx/nginx.conf:ro

  gateway:
    image: docker.io/panubo/sshd:1.0.3
    ports:
      - "2222"
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./support/gateway/sshd_config:/etc/ssh/sshd_config
      - ./support/secrets/id_rsa.pub:/root/.ssh/authorized_keys

  loophole:
    image: kroniak/ssh-client
    volumes:
      - ./support/secrets/id_rsa:/root/.ssh/id_rsa:ro
      - ./support/secrets/config:/root/.ssh/config:ro
    command: "sh -c \"sleep 5 && ssh -4 -N -R *:8080:myservice:80 gateway\""

  myservice:
    image: nginx
